export default async function syncReservations(snowflake, accessToken) {
  let dbResult

  dbResult = await snowflake.execute(`CREATE OR REPLACE TABLE reservations (
    id VARCHAR(255) PRIMARY KEY,
    bookingId VARCHAR(255),
    blockId  VARCHAR(255),
    groupName VARCHAR(255),
    status VARCHAR(255),
    checkInTime TIMESTAMP_TZ,
    checkOutTime TIMESTAMP_TZ,
    cancellationTime TIMESTAMP_TZ,
    noShowTime TIMESTAMP_TZ,
    propertyId VARCHAR(255),
    propertyCode VARCHAR(255),
    propertyName VARCHAR(255),
    ratePlanId VARCHAR(255),
    ratePlanCode VARCHAR(255),
    ratePlanIsSubjectToCityTax BOOLEAN,
    unitGroupId VARCHAR(255),
    unitGroupCode VARCHAR(255),
    unitId VARCHAR(255),
    unitName VARCHAR(255),
    totalGrossAmount NUMBER(20,2),
    totalGrossCurrency VARCHAR(255),
    arrival TIMESTAMP_TZ,
    departure TIMESTAMP_TZ,
    created TIMESTAMP_TZ,
    modified TIMESTAMP_TZ,
    adults NUMBER,
    childrenAges ARRAY,
    comment VARCHAR(255),
    guestComment VARCHAR(255),
    channelCode VARCHAR(255),
    source VARCHAR(255),
    primaryGuestTitle VARCHAR(255),
    primaryGuestGender VARCHAR(255),
    primaryGuestFirstName VARCHAR(255),
    primaryGuestMiddleInitial VARCHAR(255),
    primaryGuestLastName VARCHAR(255),
    primaryGuestEmail VARCHAR(255),
    primaryGuestPhone VARCHAR(255),
    primaryGuestAddressLine1 VARCHAR(255),
    primaryGuestAddressLine2 VARCHAR(255),
    primaryGuestPostalCode VARCHAR(255),
    primaryGuestCity VARCHAR(255),
    primaryGuestCountryCode VARCHAR(255),
    primaryGuestNationalityCountryCode VARCHAR(255),
    primaryGuestIdentificationNumber VARCHAR(255),
    primaryGuestIdentificationIssueDate DATE,
    primaryGuestIdentificationType VARCHAR(255),
    primaryGuestCompanyName VARCHAR(255),
    primaryGuestCompanyTaxId VARCHAR(255),
    primaryGuestPreferredLanguage VARCHAR(255),
    primaryGuestBirthDate DATE,
    primaryGuestBirthPlace VARCHAR(255),


    paymentAccountNumber VARCHAR(255),
    paymentAccountHolder VARCHAR(255),
    paymentAccountExpiryMonth VARCHAR(255),
    paymentAccountExpiryYear VARCHAR(255),
    paymentAccountPaymentMethod VARCHAR(255),
    paymentAccountPayerEmail VARCHAR(255),
    paymentAccountPayerReference VARCHAR(255),
    paymentAccountIsVirtual BOOLEAN,
    paymentAccountIsActive BOOLEAN,
    guaranteeType VARCHAR(255),
    cancellationFeeId VARCHAR(255),
    cancellationFeeCode VARCHAR(255),
    cancellationFeeDueDateTime TIMESTAMP_TZ,
    cancellationFeeAmount NUMBER(20,2),
    cancellationFeeCurrency VARCHAR(255),
    noShowFeeId VARCHAR(255),
    noShowFeeCode VARCHAR(255),
    noShowFeeAmount NUMBER(20,2),
    noShowFeeCurrency VARCHAR(255),
    travelPurpose VARCHAR(255),
    balanceAmount NUMBER(20,2),
    balanceCurrency VARCHAR(255),
    corporateCode VARCHAR(255),
    allFoliosHaveInvoice BOOLEAN,
    hasCityTax BOOLEAN,
    commissionAmount NUMBER(20,2),
    commissionCurrency VARCHAR(255),
    beforeCommissionAmount NUMBER(20,2),
    beforeCommissionCurrency VARCHAR(255),
    promoCode VARCHAR(255)
  )`)

  console.log(dbResult)

  const response = await fetch(
    "https://api.apaleo.com/booking/v1/reservations",
    {
      headers: {
        //'Content-Type': 'application/json',
        authorization: "Bearer " + accessToken,
      },
    }
  )

  if (!response.ok) {
    console.log(response)
    throw "Fehler"
  }

  const data = await response.json()

  console.log(data.reservations.length)

  let rows = []
  data.reservations.forEach((reservation) => {
    let row = [
      reservation.id,
      reservation.bookingId,
      reservation.blockId,
      reservation.groupName,
      reservation.status,
      reservation.checkInTime,
      reservation.checkOutTime,
      reservation.cancellationTime,
      reservation.noShowTime,
      reservation.property.id,
      reservation.property.code,
      reservation.property.name,
      reservation.ratePlan.id,
      reservation.ratePlan.code,
      reservation.ratePlan.isSubjectToCityTax,
      reservation.unitGroup.id,
      reservation.unitGroup.code,
      reservation?.unit?.id,
      reservation?.unit?.name,
      reservation.totalGrossAmount.amount,
      reservation.totalGrossAmount.currency,
      reservation.arrival,
      reservation.departure,
      reservation.created,
      reservation.modified,
      reservation.adults,
      reservation.childrenAges,
      reservation.comment,
      reservation.guestComment,
      reservation.channelCode,
      reservation.source,
      reservation.primaryGuest.title,
      reservation.primaryGuest.gender,
      reservation.primaryGuest.firstName,
      reservation.primaryGuest.middleInitial,
      reservation.primaryGuest.lastName,
      reservation.primaryGuest.email,
      reservation.primaryGuest.phone,
      reservation.primaryGuest?.address?.addressLine1,
      reservation.primaryGuest?.address?.addressLine2,
      reservation.primaryGuest?.address?.postalCode,
      reservation.primaryGuest?.address?.city,
      reservation.primaryGuest?.address?.countryCode,
      reservation.primaryGuest.nationalityCountryCode,
      reservation.primaryGuest.identificationNumber,
      reservation.primaryGuest.identificationIssueDate,
      reservation.primaryGuest.identificationType,
      reservation.primaryGuest?.company?.name,
      reservation.primaryGuest?.company?.taxId,
      reservation.primaryGuest?.preferredLanguage,
      reservation.primaryGuest?.birthDate,
      reservation.primaryGuest?.birthPlace,

      reservation.paymentAccount?.accountNumber,
      reservation.paymentAccount?.accountHolder,
      reservation.paymentAccount?.expiryMonth,
      reservation.paymentAccount?.expiryYear,
      reservation.paymentAccount?.paymentMethod,
      reservation.paymentAccount?.payerEmail,
      reservation.paymentAccount?.payerReference,
      reservation.paymentAccount?.isVirtual,
      reservation.paymentAccount?.isActive,
      reservation.guaranteeType,
      reservation.cancellationFee.id,
      reservation.cancellationFee.code,
      reservation.cancellationFee.dueDateTime,
      reservation.cancellationFee.fee.amount,
      reservation.cancellationFee.fee.currency,
      reservation.noShowFee.id,
      reservation.noShowFee.code,
      reservation.noShowFee.fee.amount,
      reservation.noShowFee.fee.currency,
      reservation.travelPurpose,
      reservation.balance.amount,
      reservation.balance.currency,
      reservation.corporateCode,
      reservation.allFoliosHaveInvoice,
      reservation.hasCityTax,

      reservation?.commission?.commissionAmount?.amount,
      reservation?.commission?.commissionAmmount?.currency,
      reservation?.commission?.beforeCommission?.amount,
      reservation?.commission?.beforeCommission?.currency,
      reservation.promoCode


    ]

    rows.push(row)
  })

  dbResult = await snowflake.execute(
    `INSERT OVERWRITE INTO reservations (id,
      bookingId,
      blockId,
      groupName,
      status,
      checkInTime,
      checkOutTime,
      cancellationTime,
      noShowTime,
      propertyId,
      propertyCode,
      propertyName,
      ratePlanId,
      ratePlanCode,
      ratePlanIsSubjectToCityTax,
      unitGroupId,
      unitGroupCode,
      unitId,
      unitName,
      totalGrossAmount,
      totalGrossCurrency,
      arrival,
      departure,
      created,
      modified,
      adults,
      childrenAges,
      comment,
      guestComment,
      channelCode,
      source,
      primaryGuestTitle,
      primaryGuestGender,
      primaryGuestFirstName,
      primaryGuestMiddleInitial,
      primaryGuestLastName,
      primaryGuestEmail,
      primaryGuestPhone,
      primaryGuestAddressLine1,
      primaryGuestAddressLine2,
      primaryGuestPostalCode,
      primaryGuestCity,
      primaryGuestCountryCode,
      primaryGuestNationalityCountryCode,
      primaryGuestIdentificationNumber,
      primaryGuestIdentificationIssueDate,
      primaryGuestIdentificationType,
      primaryGuestCompanyName,
      primaryGuestCompanyTaxId,
      primaryGuestPreferredLanguage,
      primaryGuestBirthDate,
      primaryGuestBirthPlace,


      paymentAccountNumber,
      paymentAccountHolder,
      paymentAccountExpiryMonth,
      paymentAccountExpiryYear,
      paymentAccountPaymentMethod,
      paymentAccountPayerEmail,
      paymentAccountPayerReference,
      paymentAccountIsVirtual,
      paymentAccountIsActive,

      guaranteeType,

      cancellationFeeId,
      cancellationFeeCode,
      cancellationFeeDueDateTime,
      cancellationFeeAmount,
      cancellationFeeCurrency,
      
      noShowFeeId,
      noShowFeeCode,
      noShowFeeAmount,
      noShowFeeCurrency,

      travelPurpose,

      balanceAmount,
      balanceCurrency,

      corporateCode,

      allFoliosHaveInvoice,
      hasCityTax,

      commissionAmount,
      commissionCurrency,
      beforeCommissionAmount,
      beforeCommissionCurrency,
      promoCode
      )
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
    rows
  )


  console.log(dbResult)
}